### ISSUE TITLE
Save function escapes single apostrophes in Shell Scripts

### ISSUE THREAD

**Issue by mikeono** [kronenthaler/mod-pbxproj#189]
Add a shell script with single apostrophes to your project file. For instance:

`find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK`

The load and save your project with pbxproj.

project = XcodeProject.load('DroneBasePilot.xcodeproj/project.pbxproj')
project.save()

Inspect your updated project file in a text editor and you'll see that forward slashes were added in front of the single apostrophes.

`find "$APP_PATH" -name \'*.framework\' -type d | while read -r FRAMEWORK`

Single apostrophes should not be escaped and thus the project file will not be recognized by XCode.

**Comment by kronenthaler** [comment]
Thanks for the report

**Comment by kronenthaler** [comment]
There is a Pull Request opened for this issue. However, i ran some tests and Xcode recognizes the script properly and even removes those unnecessary slashes.

Also the original script posted
```
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
```
gets escaped by xcode as 
```
find \"$APP_PATH\" -name '*.framework' -type d | while read -r FRAMEWORK
```
Even with the single quotes escaped xcode recognizes it and parses it back to the original state.

Based on this finding, i labeled to enhancement instead of a bug, since it doesn't affect the execution of the program but makes it closer to the official output.
