### ISSUE TITLE
Can I get info about the relative (physical) path of a file in the project?

### ISSUE THREAD

**Issue by foresightyj** [kronenthaler/mod-pbxproj#191]
My purpose is to identify which files in the project directories are actually present in the pbxproj file. So I am looking for a pbxproj parser. This is the closest lib I have found.  But after reading the documentation and played with the lib in iPython, I have not figured out how.

The XCodeProject object only have methods like `get_files_by_name` but none of the properties can give me anything close.

**Comment by kronenthaler** [comment]
I'm not sure i understand the question. Based on what i understand, you want to simply know if all files of the directory are in the project. Short answer: There is no direct way to know what files are added to a project. 

Long answer: It depends in great part of how they were added to the project in the first place. 
For instance, a file reference contains the path of file and the name of it. However this path is relative to something. That something is specified on the `sourceTree` of the file reference.
This is where it gets tricky, normally the `sourceTree` is `<group>`, which means that the in order to find the actual path of the file, first you need to search for the group that contains it. But groups might be also relative to other groups and so the search needs to go all the way up.
On the other hand if the file references were added with the `sourceTree=SOURCE_ROOT`, then the path on the file reference will be the one matching your expectation.
Beware that this are only 2 possible `sourceTree` values, each of the other values have their own rules. 
Because of the complexity and the limited use-case, i haven't implemented nor i have intention to write such a function.

You are free to implement this for your project, some pointers that will help out.

```
project = XcodeProject.load(...)
file_references = project.objects.get_objects_in_section('PBXFileReference')
groups = project.objects.get_objects_in_section('PBXGroup')
```

With these 2 lists, you can start navigating and reconstruct the path back.

**Comment by foresightyj** [comment]
@kronenthaler I have implemented the recursive path construction and it works really well. Thanks for the hint.
