### ISSUE TITLE
search one file's absolute path

### ISSUE THREAD

**Issue by chenxi141017** [kronenthaler/mod-pbxproj#195]
how to search one file's absolute path?

**Comment by kronenthaler** [comment]
If you mean how to find the absolute path of a file reference. Short answer: there is no direct way.

Long answer: It depends in great part of how they were added to the project in the first place.
For instance, a file reference contains the path of file and the name of it. However this path is relative to something. That something is specified on the `sourceTree` of the file reference.
This is where it gets tricky, normally the `sourceTree` is `<group>`, which means that the in order to find the actual path of the file, first you need to search for the group that contains it. But groups might be also relative to other groups and so the search needs to go all the way up.
On the other hand if the file references were added with the `sourceTree=SOURCE_ROOT`, then the path on the file reference will be the one matching your expectation.
Beware that this are only 2 possible `sourceTree` values, each of the other values have their own rules.
Because of the complexity and the limited use-case, i haven't implemented nor i have intention to write such a function.

You are free to implement this for your project, some pointers that will help out.

```
project = XcodeProject.load(...)
file_references = project.objects.get_objects_in_section('PBXFileReference')
groups = project.objects.get_objects_in_section('PBXGroup')
```

With these 2 lists, you can start navigating and reconstruct the path back.

**Comment by chenxi141017** [comment]
thank you very much
