### ISSUE TITLE
About folder manipulation

### ISSUE THREAD

**Issue by Zynke** [kronenthaler/mod-pbxproj#196]
Hello!

I know that in the wiki there is a "this subcommand is still experimental" notice, but i have a few questions about it.

Tried to add a folder and delete it. Here are my results and my questions:

## 1. Adding a folder ##

- command: `python -m pbxproj folder /Users/mac/repository/App/iOSProj.xcodeproj /Users/mac/repository/App/src/testfolder/ --recursive`

   It successfuly adds the folder in my project, but nos as expected:

- real result:

```
iOSProject
 - framework
 - src
 + testfolder
   - file1
   - file2
```
- expected result:
```
iOSProject
 - framework
 + src
   + testfolder
     - file1
     - file2
```

   Is there any way to add the /src/testfolder and its files inside the /src/ project folder and not iOSProject?

## 2. Deleting a folder ##

   After adding the folder I tried to delete it.

- command: `python -m pbxproj folder --delete /Users/mac/repository/App/iOSProj.xcodeproj /Users/mac/repository/App/src/testfolder/ --tree "<group>"`

   it throws the next error:  "An error ocurred removing one of the files"

To know what was happening I debugged the python app using the same command and parameters.

### STEP 1 ###

- class: pbxproj/pbxcli/pbxproj_folder.py

- function:

```
def _remove(project, args):
    if project.remove_files_by_path(args[u'<path>'], tree=args[u'--tree'], target_name=args[u'--target']):
        return u'Folder removed from the project.'
    raise Exception(u'An error occurred removing one of the files.')

```
remove_files_by path is called in the _remove function of the folder class.

### STEP 2 ###

- class:   pbxextensions/ProjectFiles.py

 - function:

```
def remove_files_by_path(self, path, tree=TreeType.SOURCE_ROOT, target_name=None):
    """
    Removes all files for the given path under the same tree
    :param path: Path to the file relative to the tree root
    :param tree: Tree type to look for the path. By default the SOURCE_ROOT
    :param target_name: Target name where the file should be added (none for every target)
    :return: True if all the files were removed without problems. False if at least one file failed.
    """
    files = self.get_files_by_path(path, tree)
    result = 0
    total = files.__len__()
    for file_ref in files:
        if self.remove_file_by_id(file_ref.get_id(), target_name=target_name):
            result += 1

    return result != 0 and result == total
```

Here it gets the files (not folders?) to remove calling the get_files_by_path function.

### STEP 3 ###

- function:

```
def get_files_by_path(self, path, tree=TreeType.SOURCE_ROOT):
    """
    Gets the files under the given tree type that match the given path.
    :param path: Path to the file relative to the tree root
    :param tree: Tree type to look for the path. By default the SOURCE_ROOT
    :return: List of all PBXFileReference that match the path and tree criteria.
    """
    files = []
    for file_ref in self.objects.get_objects_in_section(u'PBXFileReference'):
        if file_ref.path == path and file_ref.sourceTree == tree:
            files.append(file_ref)

    return files
```

And here it seems that it tries to get the objects inside the "project.pbxproj" that are in the "PBXFileReference" section. But there is no path that match the folder path ( /Users/mac/repository/App/src/testfolder/ ) si does not append any file_ref.

I searched the folder inside the PBXFileReference section at it seems there are only files, not folders. At least /src/testfolder and other folders are not there. Is that why does not work?

I will be very glad to know a way to delete the folder : )

Thank you!

**Comment by kronenthaler** [comment]
Thanks for you report. 
The command line options are a limited subset of what is possible to do when using the library itself.
(1) is an example of that, using the library you can specify the parent group of your folder, whereas with the CLI option you can't. Using the CLI will add everything on the top level, that's what you got. If you want to do more complex manipulations, you need to use it as a library, write a small python script that will do exactly what you need. I will mark this ticket as a improvement, because that is a common case as well, but i make no promises up to when i will be included.

As for (2), in xcode project there is no "folder" object, they either are groups or file references. The file references contain a relative-to marker (tree attribute). This attribute is needed to locate the item and delete it properly. I guess there is a mismatch between how it was added and how it was removed. If you added the folder as a group (the default) then you should remove the group. This is not supported at the moment. Again i mark this as an improvement as it's a common case.

In general, you can use the library functions directly to have more control over how things are done.

**Comment by Zynke** [comment]
Thank you very much for the answer!
I will try to write a python script ; )
