### ISSUE TITLE
plistlib.PlistWriter has been renamed to plistlib._PlistWriter in python 3

### ISSUE THREAD

**Issue by mnbittorrent** [kronenthaler/mod-pbxproj#52]
PlistWriter was never meant to be exposed in the public interface of plistlib, so it has been renamed in python 3 implementation. You can get away with just referencing _PlistWriter, but that doesn't seem viable long-term.

See:
https://hg.python.org/cpython/file/2.7/Lib/plistlib.py#l230
https://hg.python.org/cpython/file/3.4/Lib/plistlib.py#l454

**Comment by kronenthaler** [comment]
Thanks for the info. Although the python3 version is quite out dated compared to the python2 version. I'm not sure if i want to keep both versions going on, most likely i will remove the python3 version since the default python version on mac is 2.7.

I will leave this issue open until i make a decision about it or i find someone willing to keep both version in sync.

**Comment by mnbittorrent** [comment]
Sounds good. I would definitely be in favor of only having one version to worry about :)

**Comment by kronenthaler** [comment]
Python3 file has been removed!
