### ISSUE TITLE
 method "get_groups_by_name" 

### ISSUE THREAD

**Issue by huazi2015** [kronenthaler/mod-pbxproj#58]
i find a issue, this method "get_groups_by_name" also cannot use it, like this：
new_group1 = pbproject.get_groups_by_name('Test_Group')
pbproject.remove_group(new_group1.id)

error： Traceback (most recent call last):
  File "/Users/liangma/QinMoon/Editor_pbxproj/Build_pbxproj.py", line 61, in <module>
    pbproject.remove_group(new_group1.id)
AttributeError: 'list' object has no attribute 'id'
[Finished in 0.3s with exit code 1]

**Comment by huazi2015** [comment]
are you here?

**Comment by kronenthaler** [comment]
This is not an error in the project but in your code.
`new_group1 = pbproject.get_groups_by_name('Test_Group')` returns a list of groupS. Therefore, `new_group1.id` is not possible since new_group1 as a list doesn't contain a property called id.

The error is saying it. The error is in your code line 61. No trace to the project.
Please, read before start posting issues that are not.

**Comment by kronenthaler** [comment]
For the record, this is your second strike.
First strike: spamming with issues with no description and a simple vague sentence.
Second strike: an error clearly in your code.
One more strike an you will be blocked and reported for abuse. So. Think twice and validate YOUR code first before posting a fake issue.

**Comment by huazi2015** [comment]
thank you, kronenthaler . i am a china , hope you can forgiveness
